name: Flake8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Analysing the code with flake8
      run: |
        flake8 $(git ls-files 'advent_of_code/2023/day_1/*.py')
        flake8 $(git ls-files 'advent_of_code/2023/day_2/*.py')
        flake8 $(git ls-files 'ai/face_rec_system/*.py')
        flake8 $(git ls-files 'ai/gpt_standalone/*.py')
        flake8 $(git ls-files 'ai/hugging_face_hub_login/*.py')
        flake8 $(git ls-files 'ai/image_from_text/*.py')
        flake8 $(git ls-files 'ai/nlp_text_generator/*.py')
