name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "It is Your First Issue publish on this repo. Thanks from Oleg Bourdo, and happy coding :)"
        pr-message: "At last you ve done it. The future is coming on. Happy coding from Oleg Bourdo"
