name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files 'bots/telegram_bots/*.py')
        pylint $(git ls-files 'defi_example/*.py')
        pylint $(git ls-files 'simple_fast_api_array/*.py')
        pylint $(git ls-files 'ai/nlp_text_summar/*.py')
        pylint $(git ls-files 'ai/nlp_text_generator/*.py')
